# Generated by Django 4.0.4 on 2022-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='anime_title',
            field=models.CharField(default='Untitled', max_length=128),
            preserve_default=False,
        ),
    ]
