# Generated by Django 4.0.4 on 2022-04-20 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0004_comments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='anime_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='anime_app.anime'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='anime_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='anime_app.anime'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='anime_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='list', to='anime_app.anime'),
        ),
    ]
