# Generated by Django 4.0.4 on 2022-04-20 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0006_alter_anime_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='anime_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='anime_app.anime'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='anime_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='anime_app.anime'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='anime_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='anime_app.anime'),
        ),
    ]
