# Generated by Django 4.0.4 on 2022-04-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0007_alter_games_anime_title_alter_reviews_anime_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='anime_title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='anime_title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='anime_title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
