# Generated by Django 4.0.4 on 2022-04-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0008_alter_games_anime_title_alter_reviews_anime_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
