# Generated by Django 4.0.4 on 2022-04-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0010_anime_alter_games_anime_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='anime_title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='anime_title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='anime_title',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
