# Generated by Django 4.0.4 on 2022-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0013_rename_review_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='anime_title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
