# Generated by Django 4.0.4 on 2022-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0015_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='anime_title',
            field=models.CharField(max_length=128),
        ),
    ]
