# Generated by Django 4.0.4 on 2022-04-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0023_alter_watchlist_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='scores',
            new_name='score',
        ),
    ]
