# Generated by Django 4.0.4 on 2022-04-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0025_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
    ]
